name: Automated tests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        default: login_test
        type: choice
        options:
          - login_test
          - practice_test

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.1"
      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: login_test
        if: "github.event.inputs.deployment_target == 'login_test'"
        run: pytest -s -v tests/home/login_tests.py
      - name: practice_test
        if: "github.event.inputs.deployment_target == 'practice_test'"
        run: pytest -s -v tests/practice/practice_tests.py



