name: Automated tests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        default: login_test
        type: choice
        options:
          - login_test
          - practice_test
          - course_invalid_enrollment_test
          - test_suite_regress
          - all tests

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.1"
      - name: Create CSV File from Secret
        run: |
          echo -e "${{secrets.TESTDATA_CSV}}" | tr '\r' '\n' > testdata.csv
      - name: install dependencies
        run: |
          pip install -r requirements.txt
          if [[ "$RUNNER_OS" == "Windows" ]]; then pip install pywin32==306; fi
      - name: all tests
        if: "github.event.inputs.deployment_target == 'all tests'"
        run: pytest -s -v tests
      - name: login_test
        if: "github.event.inputs.deployment_target == 'login_test'"
        run: pytest -s -v tests/home/login_tests.py
#        continue-on-error: true
      - name: practice_test
        if: "github.event.inputs.deployment_target == 'practice_test'"
        run: pytest -s -v tests/practice/practice_tests.py
#        continue-on-error: true
      - name: course_invalid_enrollment_test
        if: "github.event.inputs.deployment_target == 'course_invalid_enrollment_test'"
        run: pytest -s -v tests/courses/register_courses_tests.py
#        continue-on-error: true
      - name: test_suite_regress
        if: "github.event.inputs.deployment_target == 'test_suite_regress'"
        run: pytest -s -v tests/test_suite_regress.py
#        continue-on-error: true
